@startuml

title __CONTROLLER's Class Diagram__\n
    namespace com.mareena.mediacatalogue {
      namespace controller {
        class com.mareena.mediacatalogue.controller.VideoCatalogueController {
            + VideoCatalogueController()
            + actionAddMediaItemDisable()
            + actionAddNewMedia()
            + actionDisableTitleView()
            + actionEnableAddMediaItem()
            + actionEnableLIstByGenre()
            + actionEnableLIstByYear()
            + actionEnableSelectUsers()
            + actionSelectTitle()
            + actionSelectUser()
            + actionSelectUserDisable()
            + initOtherViews()
            - initVideoCatalogue()
        }
      }
    }


  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.view.AddItem : addItemView
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.view.ListByGenre : listByGenre
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.view.ListByYear : listByYear
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.MediaCatalogueStateModel : mediaCatalogueStateModel
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.view.SelectUserView : selectUserView
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.model.VideoCatalogueModel : videoCatalogueModel
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.view.VideoCatalogue : videoCatalogueView
  com.mareena.mediacatalogue.controller.VideoCatalogueController o-- com.mareena.mediacatalogue.swing.view.ItemMediaView : viewMediaView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
